version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test

# orbs:
#     hello: circleci/hello-build@0.0.7 # circleci/buildpack-deps Docker イメージを使います

# workflows:
#     "Hello Workflow":
#         jobs:
#           - hello/hello-build

# jobs:
#   build:
#     docker: # Executor タイプです。他に machine、macOS という実行タイプを指定できます
#       - image: circleci/node:4.8.2 # プライマリコンテナです。このなかでジョブコマンドが実行されます
#     steps:
#       - checkout # プロジェクトのディレクトリにあるコードをチェックアウトします
#       - run: echo "hello world" # 「echo」コマンドを実行します